updated apt-update-security, added ubuntu/n2n-edge and etc-default

diff --git a/trunk/linux/apt-update-security b/trunk/linux/apt-update-security
--- a/trunk/linux/apt-update-security
+++ b/trunk/linux/apt-update-security
@@ -2,40 +2,43 @@
 
 # Based on https://help.ubuntu.com/community/AutomaticSecurityUpdates
 
-_adm=root@sol-5.net
-_log=/var/log/apt-security-updates
+ADMIN=
+LOG="/var/log/${0##*/}.log"
+
+[ -r "/etc/default/${0##*/}" ]  && . "/etc/default/${0##*/}"
 
 quit () {
-    [ -f "$_out" ] && rm $_out
+    [ -f "$TMP" ] && rm $TMP
     exit $1
     }
 
 error () {
-    [ -f "$_out" ] || _out=/dev/stderr	
+    [ -f "$TMP" ] || TMP=/dev/stderr	
     report "$2 ($1)" | mailer error
-    report "`date`: $2 ($1)" >> $_log-failed
+    report "`date`: $2 ($1)" >> $LOG-failed
     report "Error: $2 ($1)" >&2
     quit 1
     }
 
 report () {
     echo -e "$1"
-    [ -f "$_out" ] && sed "s/^/    /" $_out
+    [ -f "$TMP" ] && sed "s/^/    /" $TMP
     }
 
 mailer () {
-    echo "Mail -s \"apt-security-updates $1 @ `uname -nsr`\" $_adm" >> $_out 2>&1
-    mail -s "apt-security-updates $1 @ `uname -nsr`" $_adm >> $_out 2>&1
+    [ -n "$ADMIN" ] || return 1 
+    echo "Mail -s \"apt-security-updates $1 @ `uname -nsr`\" $ADMIN" >> $TMP 2>&1
+    mail -s "apt-security-updates $1 @ `uname -nsr`" $ADMIN >> $TMP 2>&1
     }
 
 run () {
-    $* >> $_out 2>&1 || error $? "command failed: $*"
+    $* >> $TMP 2>&1 || error $? "command failed: $*"
     }
 
-_out= && _out=`mktemp` && [ -f "$_out" ] || error $? "mktemp failed"
+TMP= && TMP=`mktemp` && [ -f "$TMP" ] || error $? "mktemp failed"
 run aptitude update
 run aptitude safe-upgrade -o Aptitude::Delete-Unused=false --assume-yes --target-release `lsb_release -cs`-security
-grep -q "^0 " $_out && report "No security updates available." 1>&2 && quit 0
+grep -q "^0 " $TMP && report "No security updates available." 1>&2 && quit 0
 report "Updated" | mailer success
-report "\n\n[`date`]\n" >> $_log
+report "\n\n[`date`]\n" >> $LOG
 quit 0
